name: Deploy to Google Apps Script

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install dependencies
        run: npm install
        
      - name: Install clasp
        run: npm install -g @google/clasp
        
      - name: Create clasp config
        run: |
          echo '{"scriptId":"1cts1vWklx186-1OSaRxAlA957tqtXW9lckKciISNxdVRp22ZztghkWFO","rootDir":"./"}' > .clasp.json
          
      - name: Authenticate with Google
        run: |
          echo '${{ secrets.CLASPRC_JSON }}' > ~/.clasprc.json
          
      - name: Push to Google Apps Script
        run: clasp push -f